services:
  database:
    container_name: app_database
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sql_talk
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - app/.env
volumes:
  pgdata:
